/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_harish_test_opencvcamera_NativeClass */

#ifndef _Included_com_harish_test_opencvcamera_NativeClass
#define _Included_com_harish_test_opencvcamera_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_harish_test_opencvcamera_NativeClass
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_harish_test_opencvcamera_NativeClass_getMessageFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
